### ISSUE TITLE
Web sockets error. code: "1005" reason: "Invalid Closing Frame Code: 18017"

### ISSUE THREAD

**Issue by bergwillman** [watson-intu/self-python-sdk#1]
Below is the terminal output of the error:
```
(intu-dev) C:\Users\[user]\IBM Intu\self-python-sdk>python test_topic_client.py
TopicClient Instantiated!
Topic Client is instantiated!
Connected!
On Connected function!
Sensor Manager has been instantiated!
adding sensor id: 488d31a4-9369-47cf-91e8-8552e0d24456
adding sensor id: 06a9a0d4-83ca-4a5a-8df0-f9abbbbee0ff
SpeechGesture has started!
adding gesture id: tts
Closed down 1005 Invalid Closing Frame Code: 18017
```

The same output was observed running on both a Windows 10 and Mac El Capitan. 

The line "Closed down 1005 Invalid Closing Frame Code: 18017" was printed following the call to [topic.start()](https://github.com/watson-intu/self-python-sdk/blob/master/test_topic_client.py#L71)

[The terminal output of self_instance.exe](https://github.com/watson-intu/self-python-sdk/files/994110/self_instance_log.txt)

**Comment by rolyle** [comment]
[05/11/17 11:43:53.051][ERRO][Request] Request Error 400: {"authenticated":false, "message":"You did not pass in valid auth tokens"}, URL: https://rg-gateway.mybluemix.net/v1/membership/authenticateEmbodimentsAgainstOrg
[05/11/17 11:43:53.053][STAT][TopicManager] Failed to authenticate connection 2, SelfId:  ().

**Comment by rolyle** [comment]
So it appears Intu is closing your websocket connection due to authentication issue. Make sure your python client is using the exact same bearer token on both sides.

**Comment by bergwillman** [comment]
Are those authentication credentials to be entered under "headers" in the test_topic_client.py script? I see a call out for two separate credentials, "selfID" and "token". I suppose that the token is taken from the INTU gateway credentials.

But can you clarify where to find "selfID"?

**Comment by rolyle** [comment]
In the body.json, it's called m_EmbodimentId. The m_BearerToken in the body.json contains the token you should be passing.... 

If I remember correctly, this has all been changed in the current develop branch.. :)

**Comment by bergwillman** [comment]
I was able to locate the m_EmbodimentId within the body.json file but it was empty there by default, as was the m_BearerToken. I have the most current version of both self-sdk (0.1.410.RC4), and the most recent version of Python-SDK. 

I noticed, however, that there are "m_EmbodimentId" and "parentToken" credentials within the terminal output of my first message. Would be correct to use these to fill in the body.json and the python test script? I am still receiving the same error message after attempting this. 

Where exactly in the python test script are these credentials to be input?

**Comment by bergwillman** [comment]
The m_EmbodimentId and m_BearerToken credentials can both be found within the config.json file located in the self-sdk bin directory once you successfully build INTU. The generic filepath for osx to the config.json file is the following:

self-sdk/bin/mac/config.json

Here you will find the m_BearerToken and m_EmbodimentId credentials that need to be input to the test_topic_client.py script [here](https://github.com/watson-intu/self-python-sdk/blob/master/test_topic_client.py#L67), in the two empty fields following 'selfID' and 'token'.
